### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by vanderleisp** [lavransg/Radius#1]
after initialize the app, on Firefox browser in a Windows7 machine, getting the below message after trying to enter in one of the chat rooms:

Runtime Error
Error in ./HomePage class HomePage - caused by:this.content is undefined

Stack

ChatPage@http://localhost:8100/build/main.js:54243:9 Wrapper_ChatPage@/AppModule/ChatPage/wrapper.ngfactory.js:5:18 anonymous/View_ChatPage_Host0.prototype.createInternal@/AppModule/ChatPage/host.ngfactory.js:13:24 AppView</AppView.prototype.createHostView@http://localhost:8100/build/main.js:92813:16 DebugAppView</DebugAppView.prototype.createHostView@http://localhost:8100/build/main.js:93073:20 ComponentFactory</ComponentFactory.prototype.create@http://localhost:8100/build/main.js:34879:16 NavControllerBase</NavControllerBase.prototype._viewInit@http://localhost:8100/build/main.js:27543:27 NavControllerBase</NavControllerBase.prototype._nextTrns@http://localhost:8100/build/main.js:27372:13 NavControllerBase</NavControllerBase.prototype._queueTrns@http://localhost:8100/build/main.js:27343:9 NavControllerBase</NavControllerBase.prototype.push@http://localhost:8100/build/main.js:27187:16 HomePage</HomePage.prototype.goToChat@http://localhost:8100/build/main.js:54489:9 anonymous/View_HomePage1.prototype.handleEvent_0@/AppModule/HomePage/component.ngfactory.js:493:21 DebugAppView</DebugAppView.prototype.eventHandler/<@http://localhost:8100/build/main.js:93140:24 decoratePreventDefault/<@http://localhost:8100/build/main.js:37407:36 T</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9712 NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:8100/build/main.js:35478:28 T</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9640 T</v</e.prototype.runTask@http://localhost:8100/build/polyfills.js:3:7064 t/this.invoke@http://localhost:8100/build/polyfills.js:3:10834 EventListener.handleEvent*u@http://localhost:8100/build/polyfills.js:2:27976 T</d</t.prototype.scheduleTask@http://localhost:8100/build/polyfills.js:3:9408 T</v</e.prototype.scheduleEventTask@http://localhost:8100/build/polyfills.js:3:7502 u/<@http://localhost:8100/build/polyfills.js:2:28639 addEventListener@http://localhost:8100/build/polyfills.js line 2 > Function:1:43 DomEventsPlugin</DomEventsPlugin.prototype.addEventListener@http://localhost:8100/build/main.js:53782:9 EventManager</EventManager.prototype.addEventListener@http://localhost:8100/build/main.js:14760:16 DomRenderer</DomRenderer.prototype.listen@http://localhost:8100/build/main.js:37310:16 DebugDomRenderer</DebugDomRenderer.prototype.listen@http://localhost:8100/build/main.js:91476:16 Item/renderer.listen@http://localhost:8100/build/main.js:7799:24 subscribeToRenderElement@http://localhost:8100/build/main.js:22472:26 anonymous/View_HomePage1.prototype.createInternal@/AppModule/HomePage/component.ngfactory.js:412:22 AppView</AppView.prototype.create@http://localhost:8100/build/main.js:92806:16 DebugAppView</DebugAppView.prototype.create@http://localhost:8100/build/main.js:93062:20 TemplateRef_</TemplateRef_.prototype.createEmbeddedView@http://localhost:8100/build/main.js:50679:9 ViewContainerRef_</ViewContainerRef_.prototype.createEmbeddedView@http://localhost:8100/build/main.js:50803:23 NgFor</NgFor.prototype._applyChanges/<@http://localhost:8100/build/main.js:84867:28 DefaultIterableDiffer</DefaultIterableDiffer.prototype.forEachOperation@http://localhost:8100/build/main.js:33502:17 NgFor</NgFor.prototype._applyChanges@http://localhost:8100/build/main.js:84865:9 NgFor</NgFor.prototype.ngDoCheck@http://localhost:8100/build/main.js:84859:17 anonymous/Wrapper_NgFor.prototype.ngDoCheck@/CommonModule/NgFor/wrapper.ngfactory.js:51:5 anonymous/View_HomePage0.prototype.detectChangesInternal@/AppModule/HomePage/component.ngfactory.js:253:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 anonymous/View_HomePage_Host0.prototype.detectChangesInternal@/AppModule/HomePage/host.ngfactory.js:27:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 ViewContainer</ViewContainer.prototype.detectChangesInNestedViews@http://localhost:8100/build/main.js:93205:17 anonymous/View_Nav0.prototype.detectChangesInternal@/IonicModule/Nav/component.ngfactory.js:31:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 anonymous/View_MyApp0.prototype.detectChangesInternal@/AppModule/MyApp/component.ngfactory.js:39:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 anonymous/View_MyApp_Host0.prototype.detectChangesInternal@/AppModule/MyApp/host.ngfactory.js:27:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 ViewContainer</ViewContainer.prototype.detectChangesInNestedViews@http://localhost:8100/build/main.js:93205:17 anonymous/View_IonicApp0.prototype.detectChangesInternal@/IonicModule/IonicApp/component.ngfactory.js:91:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 anonymous/View_IonicApp_Host0.prototype.detectChangesInternal@/IonicModule/IonicApp/host.ngfactory.js:27:3 AppView</AppView.prototype.detectChanges@http://localhost:8100/build/main.js:93020:9 DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:8100/build/main.js:93113:13 ViewRef_</ViewRef_.prototype.detectChanges@http://localhost:8100/build/main.js:51007:9 ApplicationRef_</ApplicationRef_.prototype.tick/<@http://localhost:8100/build/main.js:33342:75 ApplicationRef_</ApplicationRef_.prototype.tick@http://localhost:8100/build/main.js:33342:13 ApplicationRef_/<.next/<@http://localhost:8100/build/main.js:33283:99 T</d</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9092 NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvoke@http://localhost:8100/build/main.js:35487:28 T</d</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9030 T</v</e.prototype.run@http://localhost:8100/build/polyfills.js:3:6462 NgZone</NgZone.prototype.run@http://localhost:8100/build/main.js:35377:51 ApplicationRef_/<.next@http://localhost:8100/build/main.js:33283:69 EventEmitter</EventEmitter.prototype.subscribe/schedulerFn<@http://localhost:8100/build/main.js:34687:36 SafeSubscriber</SafeSubscriber.prototype.__tryOrUnsub@http://localhost:8100/build/main.js:13480:13 SafeSubscriber</SafeSubscriber.prototype.next@http://localhost:8100/build/main.js:13429:17 Subscriber</Subscriber.prototype._next@http://localhost:8100/build/main.js:13382:9 Subscriber</Subscriber.prototype.next@http://localhost:8100/build/main.js:13346:13 Subject</Subject.prototype.next@http://localhost:8100/build/main.js:15163:17 EventEmitter</EventEmitter.prototype.emit@http://localhost:8100/build/main.js:34679:54 NgZone</NgZone.prototype.checkStable@http://localhost:8100/build/main.js:35455:17 NgZone</NgZone.prototype.onLeave@http://localhost:8100/build/main.js:35522:9 NgZone</NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvoke@http://localhost:8100/build/main.js:35490:21 T</d</t.prototype.invoke@http://localhost:8100/build/polyfills.js:3:9030 T</v</e.prototype.run@http://localhost:8100/build/polyfills.js:3:6462 ZoneScheduler</ZoneScheduler.prototype.schedule@http://localhost:8100/build/main.js:11203:16 ObserveOnSubscriber</ObserveOnSubscriber.prototype.scheduleMessage@http://localhost:8100/build/main.js:28482:18 ObserveOnSubscriber</ObserveOnSubscriber.prototype._next@http://localhost:8100/build/main.js:28485:9 Subscriber</Subscriber.prototype.next@http://localhost:8100/build/main.js:13346:13 firebaseListObservable/listObs</</addFn<@http://localhost:8100/build/main.js:96416:25 g.Tb/<@http://localhost:8100/build/main.js:97054:373 ub@http://localhost:8100/build/main.js:96948:165 Rb@http://localhost:8100/build/main.js:96936:215 Sb@http://localhost:8100/build/main.js:96935:701 g.Gb@http://localhost:8100/build/main.js:97122:287 g.wd@http://localhost:8100/build/main.js:97098:246 Ce.prototype.wd@http://localhost:8100/build/main.js:97000:359 Ee/<@http://localhost:8100/build/main.js:96998:279 fd@http://localhost:8100/build/main.js:96954:462 cd.prototype.open/this.Ia.onmessage@http://localhost:8100/build/main.js:96953:67 e/e.set/n@http://localhost:8100/build/polyfills.js:2:27338 T</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9712 T</v</e.prototype.runTask@http://localhost:8100/build/polyfills.js:3:7064 t/this.invoke@http://localhost:8100/build/polyfills.js:3:10834 EventListener.handleEvent*u@http://localhost:8100/build/polyfills.js:2:27976 T</d</t.prototype.scheduleTask@http://localhost:8100/build/polyfills.js:3:9408 T</v</e.prototype.scheduleEventTask@http://localhost:8100/build/polyfills.js:3:7502 u/<@http://localhost:8100/build/polyfills.js:2:28639 addEventListener@http://localhost:8100/build/polyfills.js line 2 > Function:1:43 e/e.set@http://localhost:8100/build/polyfills.js:2:27406 cd.prototype.open@http://localhost:8100/build/main.js:96952:444 De/<@http://localhost:8100/build/main.js:96995:208 T</d</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:9712 T</v</e.prototype.runTask@http://localhost:8100/build/polyfills.js:3:7064 t/this.invoke@http://localhost:8100/build/polyfills.js:3:10834 o/e.args[0]@http://localhost:8100/build/polyfills.js:2:30114 setTimeout handler*o@http://localhost:8100/build/polyfills.js:2:30178 T</d</t.prototype.scheduleTask@http://localhost:8100/build/polyfills.js:3:9408 T</v</e.prototype.scheduleMacroTask@http://localhost:8100/build/polyfills.js:3:7372 h/u</<@http://localhost:8100/build/polyfills.js:2:30507 setTimeout@http://localhost:8100/build/polyfills.js line 2 > Function:1:37 De@http://localhost:8100/build/main.js:96995:181 Ce@http://localhost:8100/build/main.js:96994:1072 bh/<@http://localhost:8100/build/main.js:97103:481

**Comment by lavransg** [comment]
@vanderleisp 
Hello!
This is very much a work in progress and is not intended to be working properly at this time. 
I will say that the chat functionality is working on two of my windows 10 systems.
There might be some dependencies you are missing.

**Comment by vanderleisp** [comment]
Hi,
thanks.
let me check later about dependencies, if could find it.
